SuperNOVAS C++ API: Astronomical object of interest
Astronomical object of interest
Defining the astronomical source of interest, or accessing properties thereof.
Classes
class supernovas::CatalogEntry
Defines the astrometric parameters of a sidereal source, such as a star, a Galactic cloud, a distant galaxy, or a quasar.
class supernovas::CatalogSource
A sidereal source, defined by its catalog coordinates and other catalog parameters.
class supernovas::EphemerisSource
A Solar-system source, whose positions / velocities are provided from ephemeris data.
class supernovas::Equinox
Equatorial coordinate system, defining the orientation of the equator and the location of the equinox, relative to which the right ascention and declination (RA/Dec) coordinates are defined.
class supernovas::Orbital
Keplerian orbital elements, for example, for a comet using parameters published by the IAU Minor Planet Center.
class supernovas::OrbitalSource
A Solar-system source, whose position and velocity can be calculated using Keplerian orbital elements.
class supernovas::OrbitalSystem
Orbital system for Keplerian orbitals, defining the orbital plane and orientation, and the central body (such as the Sun or a planet), around which the Keplerian orbital is to be defined.
class supernovas::Planet
A major planet (including Pluto), or the Sun and the Moon, the Solar-System Barycenter (SSB), the Earth-Moon Barycenter (EMB), and the Pluto-system barycenter.
class supernovas::SolarSystemSource
An abstract class of a source in the Solar-system.
class supernovas::Source
An abstract astronomical source, or target of observation.
Macros
#define NOVAS_DEFAULT_DISTANCE (1e9 * NOVAS_PARSEC)
[m] Default distance at which sidereal sources are assumed when not specified otherwise Historically NOVAS placed sources with no parallax at 1 Gpc distance, and so we follow.
#define SIZE_OF_CAT_NAME 6
Maximum maximum bytes stored for catalog IDs including string termination.
#define SIZE_OF_OBJ_NAME 50
Maximum number of bytes stored for object names including string termination.
Functions
int novas_make_moon_mean_orbit (double jd_tdb, novas_orbital *restrict orbit)
Gets mean orbital elements for the Moon relative to the geocenter for the specified epoch of observation.
int novas_make_moon_orbit (double jd_tdb, novas_orbital *restrict orbit)
Gets an approximation of the current Keplerian orbital elements for the Moon relative to the geocenter for the specified epoch of observation.
Detailed Description
Defining the astronomical source of interest, or accessing properties thereof.
Source may be sidereal catalog sources, such as as star, molecular cloud or a distant galaxy, or else they may be Solar-system objects, such as planets, moons, asteroids, comets or near-Earth objects (NEOs). Thet may have positions and velocities provided through ephemeris data (such as the NASA JPL planetary on other ephemeris files), or else via orbital models (such as published by the IAU Minor Planet Center [MPC]).
Macro Definition Documentation
NOVAS_DEFAULT_DISTANCE
#define NOVAS_DEFAULT_DISTANCE (1e9 * NOVAS_PARSEC)
[m] Default distance at which sidereal sources are assumed when not specified otherwise Historically NOVAS placed sources with no parallax at 1 Gpc distance, and so we follow.
Since
1.5
SIZE_OF_CAT_NAME
#define SIZE_OF_CAT_NAME 6
Maximum maximum bytes stored for catalog IDs including string termination.
See also
cat_entry
Referenced by novas_set_catalog(), and transform_cat().
SIZE_OF_OBJ_NAME
#define SIZE_OF_OBJ_NAME 50
Maximum number of bytes stored for object names including string termination.
See also
cat_entry
Referenced by novas_init_cat_entry(), and transform_cat().
Function Documentation
novas_make_moon_mean_orbit()
int novas_make_moon_mean_orbit (double jd_tdb, novas_orbital *restrict orbit)
Gets mean orbital elements for the Moon relative to the geocenter for the specified epoch of observation.
It is based on the secular parameters of the ELP2000-85 model, but does not include the harmonic series and the perturbation terms. As such it has accuracy at the few degrees level only, however it is 'valid' for long-term projections (i.e. for years around the orbit's reference epoch) at that coarse level.
For the short-term , novas_make_moon_orbit() can provide somewhat more accurate predictions for up to a day or so around the reference epoch of the orbit.
REFERENCES:
Chapront, J. et al., 2002, A&A 387, 700–709
Chapront-Touze, M, and Chapront, J. 1988, Astronomy and Astrophysics, vol. 190, p. 342-352.
Chapront J., Francou G., 2003, A&A, 404, 735
Laskar J., 1986, A&A, 157, 59
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian Date.
[out] orbit Orbital elements data structure to populate.
Returns
0 if successful, or else -1 (errno set to EINVAL).
Since
1.4
Author
Attila Kovacs
See also
novas_make_moon_orbit(), novas_make_planet_orbit(), make_orbital_object()
References NOVAS_AU, NOVAS_EARTH, NOVAS_ECLIPTIC_PLANE, NOVAS_J2000, NOVAS_JD_J2000, NOVAS_ORBIT_INIT, and TWOPI.
Referenced by novas_make_moon_orbit().
novas_make_moon_orbit()
int novas_make_moon_orbit (double jd_tdb, novas_orbital *restrict orbit)
Gets an approximation of the current Keplerian orbital elements for the Moon relative to the geocenter for the specified epoch of observation.
The orbit includes the most dominant Solar perturbation terms to produce results with an accuracy at the ~10 arcmin level near (+- 0.5 days) the reference time argument of the orbit. The perturbed orbit is based on the ELP/MPP02 model.
While, the ELP/MPP02 model itself can be highly precise, the Moon's orbit is strongly non-Keplerian, and so any attempt to describe it in purely Keplerian terms is inherently flawed, which is the reason for the generally poor accuracy of this model.
REFERENCES:
Chapront, J. et al., 2002, A&A 387, 700–709
Chapront-Touze, M, and Chapront, J. 1988, Astronomy and Astrophysics, vol. 190, p. 342-352.
Chapront J., Francou G., 2003, A&A, 404, 735
Parameters
jd_tdb [day] Barycentric Dynamical Time (TDB) based Julian Date.
[out] orbit Orbital elements data structure to populate.
Returns
0 if successful, or else -1 (errno set to EINVAL).
Since
1.5.1
Author
Attila Kovacs
See also
novas_make_moon_mean_orbit(), novas_make_planet_orbit(), make_orbital_object()
References NOVAS_AU, NOVAS_JD_J2000, NOVAS_KM, and novas_make_moon_mean_orbit().
Referenced by novas_approx_heliocentric(), and novas_moon_phase().